    - name: Python Syntax Check
      run: |
        python -m compileall app

    - name: Install Vercel CLI and uv
      run: |
        npm install -g vercel
        pip install uv

    - name: Deploy to Vercel
      run: |
        vercel pull --yes \
        --environment=production \
        --token=${{ secrets.VERCEL_TOKEN }}

        vercel build \
        --prod \
        --token=${{ secrets.VERCEL_TOKEN }}

        vercel deploy \
        --prebuilt \
        --prod \
        --token=${{ secrets.VERCEL_TOKEN }}