name: Job Board CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          pip install -r requirements.txt


      - name: Python Syntax Check
        run: |
          python -m compileall app


      - name: Install Vercel CLI
        run: |
          npm install -g vercel


      - name: Install uv
        uses: astral-sh/setup-uv@v5


      - name: Check uv installation
        run: |
          uv --version


      - name: Deploy to Vercel
        working-directory: backend
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --yes --token=${{ secrets.VERCEL_TOKEN }}