name: Job Board CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install Dependencies
      run: |
        pip install -r requirements.txt


    - name: Python Syntax Check
      run: |
        python -m compileall app


    - name: Install Node and Vercel CLI
      run: |
        npm install -g vercel


    - name: Deploy to Vercel
      run: |
        vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}